AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a CodeBuild project

Resources:
  # S3 Bucket to store build artifacts
  BuildArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: test-codebuild-artifacts-bucket

  # IAM Role for CodeBuild
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: Allow
            Principal: 
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies: 
        - PolicyName: CodeBuildPolicy
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: Allow
                Resource: 
                  - arn:aws:s3:::test-codebuild-artifacts-bucket
                  - arn:aws:s3:::test-codebuild-artifacts-bucket/*
                Action: 
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
              - Effect: Allow
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/SampleCodeBuildProject
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/SampleCodeBuildProject:*
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
              - Effect: Allow
                Resource:
                  - !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/SampleCodeBuildProject-*
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: SampleCodeBuildProject
      Source:
        Type: GITHUB
        Location: https://github.com/dieni/aws-cicd
      Artifacts:
        Type: S3
        Location: !Ref BuildArtifactsBucket
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
