AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a CodeBuild project

Parameters:
  BucketName:
    Default: codebuild-artifacts-cicd
    Type: String
    Description: S3 bucket to store the artefacts of CodeBuild
  CodeBuildName:
    Default: github-cicd
    Type: String
    Description: The name of the CodeBuild project
  GitHubRepo:
    Default: https://github.com/dieni/aws-cicd # Remove me
    Type: String
    Description: The URL to the GitHub repository
  

Resources:
  # S3 Bucket to store build artifacts
  BuildArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  # IAM Role for CodeBuild
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: Allow
            Principal: 
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies: 
        - PolicyName: CodeBuildPolicy
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: Allow
                Resource: 
                  - !Sub arn:aws:s3:::${BucketName}
                  - !Sub arn:aws:s3:::${BucketName}/*
                Action: 
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
              - Effect: Allow
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${CodeBuildName}
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${CodeBuildName}:*
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
              - Effect: Allow
                Resource:
                  - !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/${CodeBuildName}-*
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref CodeBuildName
      Source:
        Type: GITHUB
        Location: !Ref GitHubRepo
      Triggers:
        Webhook: true
        FilterGroups:
        - - Type: EVENT
            Pattern: WORKFLOW_JOB_QUEUED
      Artifacts:
        Type: S3
        Location: !Ref BuildArtifactsBucket
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
