AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an OIDC identity provider for GitHub.

Parameters:
  ConditionKey: # Update to your needs
    Default: repo:dieni/*
    Type: String
    Description: Evaluating this condition key in the role trust policy limits which GitHub actions are able to assume the role.
  GitHubActionsRoleName: # Update to your needs
    Default: GitHubActionsRole
    Type: String
    Description: The name of the role that is used by the OIDC provider.
  ECRAccessPolicyName: # Update to your needs
    Default: ECRAccessPolicy
    Type: String
    Description: The name of the policy that is attached to the IAM role.


Resources:
  GitHubOIDCProvider:
    Type: 'AWS::IAM::OIDCProvider'
    Properties: 
      Url: 'https://token.actions.githubusercontent.com'
      ClientIdList: 
        - 'sts.amazonaws.com'
      ThumbprintList: 
        - '1b511abead59c6ce207077c0bf0e0043b1382612' # This is the thumbprint for GitHub's root CA certificate

  GitHubActionsRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      RoleName: !Ref GitHubActionsRoleName
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: 'Allow'
            Principal: 
              Federated: !GetAtt GitHubOIDCProvider.Arn
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition: 
              StringEquals: 
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
              StringLike: 
                'token.actions.githubusercontent.com:sub': '${ConditionKey}'
      Policies:
        - PolicyName: !Ref ECRAccessPolicyName
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Allow'
                Action: 
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:PutImage'
                  - 'ecr:InitiateLayerUpload'
                  - 'ecr:UploadLayerPart'
                  - 'ecr:CompleteLayerUpload'
                Resource: 
                  - '*' # Todo: Restrict access based on limited privileges

Outputs:
  GitHubOIDCProviderArn:
    Description: 'The ARN of the created GitHub OIDC provider'
    Value: !GetAtt GitHubOIDCProvider.Arn

  GitHubActionsRoleArn:
    Description: 'The ARN of the role to be assumed by GitHub Actions'
    Value: !GetAtt GitHubActionsRole.Arn