name: Build and Push
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
env:
  AWS_REGION : "eu-central-1"
  IMAGE_TAG: ${{ github.sha }}
permissions:
  id-token: write # This is required for oidc
  contents: read  # This is required for actions/checkout

jobs:
  Build-and-Push:
    runs-on: codebuild-github-cicd-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::058264264767:role/GitHubActionsRole # Update to your needs
            aws-region: ${{ env.AWS_REGION }}
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2
        - name: Build, tag, and push docker image to Amazon ECR
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: my-app # Update to your needs
            IMAGE_TAG: ${{ github.sha }}
          run: |
            docker build -f docker/.Dockerfile -t "$REGISTRY/$REPOSITORY:$IMAGE_TAG" .
            docker push "$REGISTRY/$REPOSITORY:$IMAGE_TAG"

