name: Build and Push
on:
  push: # Change to on merge
    paths-ignore:
      - '**.md'
env:
  AWS_REGION : "eu-central-1"
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  Build-and-Push:
    runs-on: codebuild-github-cicd-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::058264264767:role/GitHub-Actions
            aws-region: ${{ env.AWS_REGION }}
        - name: Docker login to ECR
          run: make docker_login
        - name: Build docker image
          run: make docker_build
        - name: Push docker image
          run: make docker_push





