name: Unit Tests
on: [push]
jobs:
  Unit-Tests:
    runs-on: codebuild-GitHubRunner-aws-cicd-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run unit tests
        run: make test_unit