name: Unit Tests
on:
  push:
    paths-ignore:
      - '**.md'
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  Unit-Tests:
    runs-on: codebuild-github-cicd-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install virtual envrionment
        run: poetry install
      - name: Run unit tests
        run: make test_unit

  